name: Nightly Build

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs at 12:00 AM UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dingjunyu888/nightly-build

      - name: Run tests
        run: |
          docker run --rm \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e JWT_ALGORITHM=${{ secrets.JWT_ALGORITHM }} \
            -e MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} \
            -e MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
            -e MAIL_FROM=${{ secrets.MAIL_FROM }} \
            -e MAIL_PORT=${{ secrets.MAIL_PORT }} \
            -e MAIL_SERVER=${{ secrets.MAIL_SERVER }} \
            -e MAIL_FROM_NAME=${{ secrets.MAIL_FROM_NAME }} \
            -e DOMAIN=${{ secrets.DOMAIN }} \
            dingjunyu888/fastapi-beyond-crud:latest \
            python -m pytest
      - name: Notify on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Nightly Build Failed
          body: The nightly build and test of your application failed.
          to: dingjunyu888@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
          secure: false
