name: Nightly Build

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs at 12:00 AM UTC every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: yourusername/yourapp:latest

      - name: Run tests
        run: docker run --rm yourusername/yourapp:latest /path/to/your/tests

      - name: Notify on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Nightly Build Failed
          body: The nightly build and test of your application failed.
          to: user@example.com
          from: ${{ secrets.MAIL_USERNAME }}
          secure: false
