name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 12:00 AM UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create and Load Environment Variables
        run: |
          cp .env.example .env
          while IFS='=' read -r key value
          do
            # Using echo to set GitHub environment variables
            echo "$key=$value" >> $GITHUB_ENV
          done < <(grep -v '^#' .env)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dingjunyu888/nightly-build

      - name: Run tests
        run: |
          source env/bin/activate
          pip install pytest
          pytest src/tests/

      - name: Notify on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Nightly Build Failed
          body: The nightly build and test of your application failed.
          to: dingjunyu888@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
          secure: false
